server:
  session-timeout: 1800
  port: 80

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  devtools:
    restart:
      enabled: true
